/**
 * Secrets and hidden truths for colonist backstories
 */

export const SECRETS = [
  "killed someone in self-defense but told no one",
  "are fleeing from a vengeful ex-lover",
  "witnessed a murder and never reported it",
  "stole a large sum of money years ago",
  "have a child they abandoned",
  "are addicted to a rare substance",
  "are actually nobility in hiding",
  "deserted from the military",
  "were part of a dark cult",
  "know the location of hidden treasure",
  "have a terminal illness they're hiding",
  "were in prison for a crime they did commit",
  "are being blackmailed by someone from their past",
  "have a twin they've never mentioned",
  "once practiced forbidden magic",
  "can't read but have memorized hundreds of books by listening",
  "stole the identity of someone who died",
  "once betrayed their best friend for money",
  "are slowly losing their memory",
  "hear voices that sometimes predict disasters",
  "were present at a famous historical event but under a different name",
  "burned down their family home and let everyone think it was an accident",
  "know a cure for a rare disease but keep it hidden",
  "were once married to three people simultaneously",
  "witnessed a murder by someone powerful and never spoke up",
  "have a twin who committed crimes in their name",
  "can communicate with animals but think they're going mad",
  "once worked as an executioner",
  "are being hunted by a vengeful crime family",
  "faked their own death twice",
  "have a treasure map tattooed on their body",
  "poisoned someone years ago and were never caught",
  "can't feel physical pain",
  "are immortal, or at least haven't aged in decades",
  "know the true name of an ancient demon"
];
